# fly.toml app configuration file generated for ais-tracker-black-shadow-3311 on 2026-04-11T15:00:47-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ais-tracker-black-shadow-3311'
primary_region = 'sjc'

[build]

[env]
  SERVER_HOST = '0.0.0.0'
  SERVER_PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
